# Generated by Django 5.0.1 on 2024-01-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='quantidade_perguntas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='categoria',
        ),
        migrations.CreateModel(
            name='FlashcardDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido', models.BooleanField(default=False)),
                ('acertou', models.BooleanField(default=False)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flashcards.flashcard')),
            ],
        ),
        migrations.AddField(
            model_name='desafio',
            name='flashcards',
            field=models.ManyToManyField(to='flashcards.flashcarddesafio'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='categoria',
            field=models.ManyToManyField(to='flashcards.categoria'),
        ),
    ]
